baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Zach Alexander"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
  text_color = ""
  author = "Zach Alexander"
  favicon = ""
  site_logo = ""
  description = "Senior software engineer at Amazon. I do all things web."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner-snow-image.jpg"
  recent_posts_number = 5
  disable_share = true

[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/zpalexander"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/zpalexander"
